### ISSUE TITLE
Replacing aget with goog.object/get

### ISSUE THREAD

**Issue by olivergeorge** [seantempesta/cljs-react-navigation#11]
I think it's considered bad practice to use aget for objects.  It works due to the generated javascript code but should be reserved for array access.

The alternative is goog.object/get.

Fix would be a search and replace for aget in the base ns, replacing with gobj/get.

Note: I'm no expert on the matter.

**Comment by dotemacs** [comment]
Mike Fikes talks about it in his blog:

http://blog.fikesfarm.com/posts/2017-11-09-avoid-converting-javascript-objects.html

Is this something that would be of interest to implement?

**Comment by dotemacs** [comment]
@olivergeorge thanks for bringing this up, it has now been implemented with the PR #12 

I'll close this for now, thanks
