### ISSUE TITLE
DrawerNavigator wrapper

### ISSUE THREAD

**Issue by EuAndreh** [seantempesta/cljs-react-navigation#3]
I've noticed that the `DrawerNavigator` isn't properly wrapped like `StackNavigator`.

Is there any special reason for not doing so? Is there anybody working on it as of today?

If not, I could happily add that. Would you be interested in it?

By the way, thanks for the library :)

**Comment by seantempesta** [comment]
Thanks!  Yeah, I never wrapped it because I've never used it.  Would love a PR.  :)

**Comment by andrew-nguyen** [comment]
@EuAndreh Did you end up working on this? I'm finding a need for it myself.  Would be happy to continue from where you left off if you have anything.

**Comment by EuAndreh** [comment]
@andrew-nguyen Unfortunately, I have not. @seantempesta should I close this issue?

**Comment by seantempesta** [comment]
Nah.  I'll eventually get around to this.  I started doing a large refactor and got sidetracked with another project.

**Comment by carocad** [comment]
@seantempesta I am in need of this myself as well. If it is a simple change (I guess it is) I would like to submit a PR for it.

Just give me some general instructions and I will find my way through

**Comment by carocad** [comment]
In case anyone is interested. I just created `drawer-navigator` and `drawer-screen` options in one of my projects. The code follows the same pattern as the one from @seantempesta. I am hoping that it will eventually be merged but after implementing it I realized why the need to refactor the original project code :)

- definitions: https://github.com/hiposfer/hive/blob/reagent/src/hive/components/navigation.cljs
- usage: https://github.com/hiposfer/hive/blob/reagent/src/hive/core.cljs#L15

feedback welcome

**Comment by vsrinivas150283** [comment]
I am looking at re-frame implementation of drawer-navigator. It doesn't seem to work like stack-navigator when using router

**Comment by dotemacs** [comment]
I take it that this issue is resolved by the #9 and can be closed ?
